# Processing Function Parameters
imputer_strategy : median



# Features for Train Process
num_attribs:
 - longitude
 - latitude
 - housing_median_age
 - total_rooms
 - total_bedrooms
 - population
 - households
 - median_income

cat_attribs: 
- ocean_proximity
