# Package Overview
package_name: regression_model

# Data Files
data_path: datasets
training_data_name: train_data.csv
test_data_name: test_data.csv

# Model Features
target_name: median_house_value


# Model Save Directory
model_save_directory: trained_model
model_name: reg_pred
model_version: 0.1


